# Generated by Django 3.1.5 on 2021-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostINfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('penrson_name', models.CharField(max_length=30)),
                ('compny_name', models.CharField(max_length=30)),
                ('town_city', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=300)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
