# Generated by Django 3.1.5 on 2021-10-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jubba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costinfo',
            old_name='penrson_name',
            new_name='File_name',
        ),
        migrations.RemoveField(
            model_name='costinfo',
            name='pdf',
        ),
    ]
